/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StagingRouteImport } from './routes/staging'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OutcomeRouteImport } from './routes/outcome'
import { Route as BoxRouteImport } from './routes/box'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as IngestionIndexRouteImport } from './routes/ingestion.index'
import { Route as SettingsSourcesRouteImport } from './routes/settings.sources'
import { Route as SettingsAgentRouteImport } from './routes/settings.agent'
import { Route as IngestionSourceIdRouteImport } from './routes/ingestion.$sourceId'
import { Route as SettingsSourcesSourceIdRouteImport } from './routes/settings.sources.$sourceId'

const StagingRoute = StagingRouteImport.update({
  id: '/staging',
  path: '/staging',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomeRoute = OutcomeRouteImport.update({
  id: '/outcome',
  path: '/outcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxRoute = BoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const IngestionIndexRoute = IngestionIndexRouteImport.update({
  id: '/ingestion/',
  path: '/ingestion/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSourcesRoute = SettingsSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentRoute = SettingsAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => SettingsRoute,
} as any)
const IngestionSourceIdRoute = IngestionSourceIdRouteImport.update({
  id: '/ingestion/$sourceId',
  path: '/ingestion/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSourcesSourceIdRoute = SettingsSourcesSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => SettingsSourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/box': typeof BoxRoute
  '/outcome': typeof OutcomeRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staging': typeof StagingRoute
  '/ingestion/$sourceId': typeof IngestionSourceIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/sources': typeof SettingsSourcesRouteWithChildren
  '/ingestion/': typeof IngestionIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/sources/$sourceId': typeof SettingsSourcesSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/box': typeof BoxRoute
  '/outcome': typeof OutcomeRoute
  '/staging': typeof StagingRoute
  '/ingestion/$sourceId': typeof IngestionSourceIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/sources': typeof SettingsSourcesRouteWithChildren
  '/ingestion': typeof IngestionIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/sources/$sourceId': typeof SettingsSourcesSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/box': typeof BoxRoute
  '/outcome': typeof OutcomeRoute
  '/settings': typeof SettingsRouteWithChildren
  '/staging': typeof StagingRoute
  '/ingestion/$sourceId': typeof IngestionSourceIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/sources': typeof SettingsSourcesRouteWithChildren
  '/ingestion/': typeof IngestionIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/sources/$sourceId': typeof SettingsSourcesSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/box'
    | '/outcome'
    | '/settings'
    | '/staging'
    | '/ingestion/$sourceId'
    | '/settings/agent'
    | '/settings/sources'
    | '/ingestion/'
    | '/settings/'
    | '/settings/sources/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/box'
    | '/outcome'
    | '/staging'
    | '/ingestion/$sourceId'
    | '/settings/agent'
    | '/settings/sources'
    | '/ingestion'
    | '/settings'
    | '/settings/sources/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/box'
    | '/outcome'
    | '/settings'
    | '/staging'
    | '/ingestion/$sourceId'
    | '/settings/agent'
    | '/settings/sources'
    | '/ingestion/'
    | '/settings/'
    | '/settings/sources/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  BoxRoute: typeof BoxRoute
  OutcomeRoute: typeof OutcomeRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StagingRoute: typeof StagingRoute
  IngestionSourceIdRoute: typeof IngestionSourceIdRoute
  IngestionIndexRoute: typeof IngestionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staging': {
      id: '/staging'
      path: '/staging'
      fullPath: '/staging'
      preLoaderRoute: typeof StagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcome': {
      id: '/outcome'
      path: '/outcome'
      fullPath: '/outcome'
      preLoaderRoute: typeof OutcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box': {
      id: '/box'
      path: '/box'
      fullPath: '/box'
      preLoaderRoute: typeof BoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/ingestion/': {
      id: '/ingestion/'
      path: '/ingestion'
      fullPath: '/ingestion/'
      preLoaderRoute: typeof IngestionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sources': {
      id: '/settings/sources'
      path: '/sources'
      fullPath: '/settings/sources'
      preLoaderRoute: typeof SettingsSourcesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agent': {
      id: '/settings/agent'
      path: '/agent'
      fullPath: '/settings/agent'
      preLoaderRoute: typeof SettingsAgentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/ingestion/$sourceId': {
      id: '/ingestion/$sourceId'
      path: '/ingestion/$sourceId'
      fullPath: '/ingestion/$sourceId'
      preLoaderRoute: typeof IngestionSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sources/$sourceId': {
      id: '/settings/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/settings/sources/$sourceId'
      preLoaderRoute: typeof SettingsSourcesSourceIdRouteImport
      parentRoute: typeof SettingsSourcesRoute
    }
  }
}

interface SettingsSourcesRouteChildren {
  SettingsSourcesSourceIdRoute: typeof SettingsSourcesSourceIdRoute
}

const SettingsSourcesRouteChildren: SettingsSourcesRouteChildren = {
  SettingsSourcesSourceIdRoute: SettingsSourcesSourceIdRoute,
}

const SettingsSourcesRouteWithChildren = SettingsSourcesRoute._addFileChildren(
  SettingsSourcesRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAgentRoute: typeof SettingsAgentRoute
  SettingsSourcesRoute: typeof SettingsSourcesRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAgentRoute: SettingsAgentRoute,
  SettingsSourcesRoute: SettingsSourcesRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  BoxRoute: BoxRoute,
  OutcomeRoute: OutcomeRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StagingRoute: StagingRoute,
  IngestionSourceIdRoute: IngestionSourceIdRoute,
  IngestionIndexRoute: IngestionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
