INSERT INTO requests (id,title,description,product_area,primary_source,frequency,confidence,user_type,status,jira_key,impact_value,impact_rationale,reach_value,reach_rationale,urgency_value,urgency_rationale,effort_value,effort_rationale,created_at) VALUES
(
  'req_001', 'Bulk approval for SAR filings', 'Compliance officers spend significant time approving Suspicious Activity Reports one by one. They want to multi-select filings in the queue and approve in a single action, with an aggregated audit trail.',
  'Transaction Monitoring', 'Email', 7, 0.92,
  'Compliance Officer', 'new', NULL,
  88, 'Eliminates a daily 90-minute bottleneck for tier-1 compliance teams; tied to retention conversations with two top-10 clients.',
  78, 'Requested by 7 clients across 3 countries, including 2 enterprise tier.',
  72, 'Q3 AMLD6 deadline raises filing volume — clients want this before September.',
  55, 'Backend bulk handler exists; mostly UI work and audit-log changes.',
  '2026-05-26T09:00:00.000Z'
),
(
  'req_002', 'Bulk approve flagged transactions', 'Same need as bulk SAR approval but for the transaction review queue — likely a duplicate cluster candidate.',
  'Transaction Monitoring', 'Teams', 3, 0.81,
  'Compliance Officer', 'new', NULL,
  80, 'Significant time savings for review teams.',
  60, '3 clients asking, overlapping with SAR request.',
  65, 'Linked to year-end review load.',
  60, 'Reuses same bulk infrastructure.',
  '2026-05-25T09:00:00.000Z'
),
(
  'req_003', 'Export risk scores to CSV with custom columns', 'Analysts want to choose which columns appear in CSV exports of the risk register, then save the column preset for re-use.',
  'Risk Engine', 'Email', 5, 0.88,
  'Risk Analyst', 'new', NULL,
  62, 'Quality-of-life win; analysts currently post-process in Excel.',
  70, '5 clients, mostly mid-market analytics teams.',
  35, 'No deadline tied to it.',
  78, 'Small frontend change, existing export endpoint.',
  '2026-05-23T09:00:00.000Z'
),
(
  'req_004', 'Two-factor auth via hardware key (FIDO2)', 'Enterprise clients require WebAuthn / FIDO2 support for admin logins. Currently only TOTP is supported.',
  'Admin Console', 'Read.AI', 4, 0.95,
  'Compliance Officer', 'new', NULL,
  90, 'Blocker for 2 active enterprise deals (~€480k ARR).',
  55, 'Smaller cohort but high-value.',
  85, 'One deal expects answer within 4 weeks.',
  40, 'Library integration + admin UI + recovery flow.',
  '2026-05-27T09:00:00.000Z'
),
(
  'req_005', 'Dark mode for client portal', 'End users have asked for a dark theme, particularly trading desks working late hours.',
  'Client Portal', 'Teams', 9, 0.78,
  'KYC Analyst', 'new', NULL,
  35, 'Cosmetic; no revenue tie identified.',
  80, 'Most-requested QoL item this quarter.',
  20, 'No deadline.',
  35, 'Touches every screen — meaningful design+QA effort.',
  '2026-05-20T09:00:00.000Z'
),
(
  'req_006', 'KYC document re-request workflow', 'When a KYC document is rejected, ops want a templated one-click request back to the client with the rejection reason auto-populated.',
  'KYC', 'Email', 6, 0.9,
  'Compliance Officer', 'new', NULL,
  75, 'Cuts onboarding time on rejections from ~3 days to ~1 day.',
  72, 'All KYC-using clients (6 named).',
  55, 'Painful but not blocking.',
  60, 'Template engine exists; mostly workflow + email.',
  '2026-05-21T09:00:00.000Z'
),
(
  'req_007', 'Configurable report scheduling (weekly/monthly)', 'Clients want to schedule recurring reports rather than running them manually each period.',
  'Reporting', 'Email', 8, 0.93,
  'Operations Lead', 'new', NULL,
  70, 'Frees ~2 hours/week per client analyst.',
  85, '8 clients, broad applicability.',
  50, 'Workaround exists (manual runs).',
  50, 'Need scheduler + delivery + retry logic.',
  '2026-05-24T09:00:00.000Z'
),
(
  'req_008', 'PDF report templates with client branding', 'Allow uploading a logo and brand color set applied to all generated PDFs.',
  'Reporting', 'Read.AI', 4, 0.84,
  'Client Admin', 'new', NULL,
  50, 'Helps client-facing presentation, no direct revenue.',
  60, '4 mid-market clients.',
  30, 'Nice-to-have.',
  55, 'Template engine refactor.',
  '2026-05-18T09:00:00.000Z'
),
(
  'req_009', 'Audit log filtering by user + action type', 'Compliance leads need to filter the system audit log by combinations of user, action, and date range.',
  'Admin Console', 'Teams', 3, 0.87,
  'Compliance Officer', 'new', NULL,
  65, 'Cuts incident-investigation time materially.',
  45, 'Compliance teams only, 3 clients.',
  60, 'Tied to upcoming audit at one client.',
  65, 'Index + UI filters; backend already logs everything.',
  '2026-05-26T09:00:00.000Z'
),
(
  'req_010', 'Inline comments on risk register rows', 'Let analysts attach short comments to individual risk rows for context.',
  'Risk Engine', 'Teams', 2, 0.7,
  'Exec Sponsor', 'new', NULL,
  40, 'Collaboration improvement, modest.',
  30, 'Only 2 mentions so far.',
  25, 'Slack/Teams used today as workaround.',
  65, 'Comments service + UI.',
  '2026-05-17T09:00:00.000Z'
),
(
  'req_011', 'SSO via Okta / Azure AD', 'Enterprise clients want SAML SSO with their existing IdP.',
  'Admin Console', 'Read.AI', 5, 0.96,
  'Risk Analyst', 'new', NULL,
  82, 'Removes a procurement blocker for enterprise deals.',
  65, '5 clients, all upper tier.',
  70, 'Two deals waiting on this.',
  45, 'SAML lib + provisioning + admin UI.',
  '2026-05-22T09:00:00.000Z'
),
(
  'req_012', 'Mobile-responsive dashboards', 'Client portal dashboards break below 768px width.',
  'Client Portal', 'Email', 3, 0.83,
  'KYC Analyst', 'new', NULL,
  45, 'Most users on desktop; mobile is occasional.',
  50, '3 clients, but execs view on phones.',
  30, 'Workaround: open on laptop.',
  40, 'Significant responsive rewrite.',
  '2026-05-19T09:00:00.000Z'
),
(
  'req_013', 'Webhook on transaction-flag events', 'Tech-savvy clients want outbound webhooks so their internal systems react to flag events.',
  'Transaction Monitoring', 'Teams', 4, 0.89,
  'Operations Lead', 'new', NULL,
  60, 'Unlocks automation downstream of monitoring.',
  50, '4 technical clients.',
  40, 'No hard deadline.',
  55, 'Webhook infra + retries + signature.',
  '2026-05-25T09:00:00.000Z'
),
(
  'req_014', 'Saved filter views in transaction queue', 'Save filter combinations as named views (e.g. ''High-risk EUR > 10k'').',
  'Transaction Monitoring', 'Email', 6, 0.91,
  'Client Admin', 'new', NULL,
  60, 'Speeds up daily triage.',
  70, 'Most monitoring users.',
  45, 'Productivity win.',
  70, 'Localstorage or per-user persistence.',
  '2026-05-23T09:00:00.000Z'
),
(
  'req_015', 'Bulk-edit client metadata in KYC', 'Update country code / segment for many client records at once.',
  'KYC', 'Teams', 2, 0.74,
  'Exec Sponsor', 'new', NULL,
  50, 'Useful for periodic data cleanup.',
  30, '2 mentions.',
  20, 'No deadline.',
  50, 'Validation + audit.',
  '2026-05-15T09:00:00.000Z'
),
(
  'req_016', 'Slack integration for alerts', 'Forward configured alerts into a Slack channel.',
  'Admin Console', 'Email', 4, 0.86,
  'Risk Analyst', 'new', NULL,
  55, 'Faster alert response.',
  55, '4 clients, Slack-using.',
  40, 'Email alerts work today.',
  75, 'Slack OAuth + simple webhook poster.',
  '2026-05-24T09:00:00.000Z'
),
(
  'req_017', 'Multi-currency display in reports', 'Show monetary values in client''s preferred currency, not just EUR.',
  'Reporting', 'Read.AI', 3, 0.8,
  'KYC Analyst', 'new', NULL,
  65, 'Removes manual conversion for non-EUR clients.',
  45, '3 non-EUR clients.',
  55, 'Asked repeatedly.',
  50, 'FX source + per-report toggle.',
  '2026-05-21T09:00:00.000Z'
),
(
  'req_018', 'Risk score change history per entity', 'Show timeline of how an entity''s risk score evolved with reasons.',
  'Risk Engine', 'Teams', 3, 0.82,
  'Compliance Officer', 'new', NULL,
  70, 'Critical for audit defensibility.',
  45, 'Compliance + risk teams.',
  55, 'Tied to audit cycles.',
  55, 'Event-sourcing of score changes.',
  '2026-05-22T09:00:00.000Z'
),
(
  'req_019', 'Tooltip explanations on risk indicators', 'Hover tooltips that explain what each risk indicator means.',
  'Risk Engine', 'Email', 2, 0.68,
  'Operations Lead', 'new', NULL,
  30, 'Helps new users; docs cover this elsewhere.',
  25, '2 mentions.',
  15, 'No urgency.',
  85, 'Trivial content addition.',
  '2026-05-16T09:00:00.000Z'
),
(
  'req_020', 'API rate-limit transparency in client portal', 'Show clients their current API usage vs. their plan limits.',
  'Client Portal', 'Teams', 3, 0.85,
  'Client Admin', 'new', NULL,
  45, 'Reduces support tickets about rate limits.',
  40, 'API-using clients.',
  30, 'Workaround: ask support.',
  60, 'Read-only metering page.',
  '2026-05-23T09:00:00.000Z'
),
(
  'req_021', 'Re-run rules on historical transactions', 'After a rule change, re-evaluate past 30/60/90 days of transactions.',
  'Transaction Monitoring', 'Read.AI', 3, 0.88,
  'Compliance Officer', 'new', NULL,
  78, 'Closes a compliance gap when rules tighten.',
  50, 'Compliance-driven clients.',
  65, 'Asked after regulatory updates.',
  35, 'Heavy batch job + safe-mode flags.',
  '2026-05-24T09:00:00.000Z'
),
(
  'req_022', 'User-defined risk thresholds per segment', 'Allow ops to set different risk cutoffs per client segment.',
  'Risk Engine', 'Email', 4, 0.87,
  'Exec Sponsor', 'reviewed', NULL,
  70, 'More precise targeting reduces false positives.',
  55, '4 clients with segmentation strategy.',
  45, 'Roadmap-aligned.',
  50, 'Config UI + engine support.',
  '2026-05-19T09:00:00.000Z'
),
(
  'req_023', 'Export audit log to SIEM-compatible format', 'Native CEF/LEEF export for security teams.',
  'Admin Console', 'Teams', 2, 0.79,
  'Compliance Officer', 'new', NULL,
  60, 'Important for enterprise security posture.',
  30, '2 enterprise-tier clients.',
  50, 'Requested in security questionnaires.',
  60, 'Format adapter + scheduled export.',
  '2026-05-20T09:00:00.000Z'
),
(
  'req_024', 'Faster initial portal load', 'Client portal first-paint feels slow on cold loads.',
  'Client Portal', 'Email', 5, 0.72,
  'Risk Analyst', 'new', NULL,
  55, 'Perception issue impacting NPS.',
  70, 'All portal users.',
  40, 'Slow-cooking issue.',
  30, 'Real perf work — could be deep.',
  '2026-05-14T09:00:00.000Z'
),
(
  'req_025', 'Light-mode toggle in admin', 'Some admins prefer light mode at their desk monitors.',
  'Admin Console', 'Teams', 1, 0.55,
  'KYC Analyst', 'new', NULL,
  20, 'Single requester.',
  15, '1 mention.',
  10, 'None.',
  40, 'Theme work everywhere.',
  '2026-05-13T09:00:00.000Z'
);

INSERT INTO source_mentions (id,request_id,source,author,client,excerpt,link,ts) VALUES
('m1', 'req_001', 'Email', 'Sandra Voss', 'NordBank AS', 'Our team approves 200+ SARs weekly — clicking each one is killing throughput. Can we get a bulk action?', '#', '2026-05-26T09:00:00.000Z'),
('m2', 'req_001', 'Teams', 'Lukas Meyer', 'Helvetia Trust', 'Multi-select approve please. Even 10 at a time would save hours.', '#', '2026-05-24T09:00:00.000Z'),
('m3', 'req_001', 'Read.AI', 'QBR with FinSquare', 'FinSquare', 'Customer raised SAR queue performance as the #1 friction point. Asked for batch ops explicitly.', '#', '2026-05-22T09:00:00.000Z'),
('m4', 'req_002', 'Teams', 'Anika Roth', 'Helvetia Trust', 'Could we batch-approve low-risk flagged tx the same way?', '#', '2026-05-25T09:00:00.000Z'),
('m5', 'req_003', 'Email', 'Marc Dubois', 'Parisien Capital', 'The CSV always includes columns we don''t need. Can we pick?', '#', '2026-05-23T09:00:00.000Z'),
('m6', 'req_004', 'Read.AI', 'Procurement call — BlauBank', 'BlauBank', 'Security team won''t approve onboarding without hardware-key support. This is a hard requirement.', '#', '2026-05-27T09:00:00.000Z'),
('m7', 'req_005', 'Teams', 'Various', 'Multiple', 'Aggregated from 9 separate mentions across client channels.', '#', '2026-05-20T09:00:00.000Z'),
('m8', 'req_006', 'Email', 'Tessa Vandermeer', 'DeltaPay', 'Rejection emails are written from scratch every time. Big time sink.', '#', '2026-05-21T09:00:00.000Z'),
('m9', 'req_007', 'Email', 'Ingrid Hofstede', 'AmsterFin', 'Please let me set the monthly close report to run on the 1st automatically.', '#', '2026-05-24T09:00:00.000Z'),
('m10', 'req_008', 'Read.AI', 'QBR — Parisien', 'Parisien Capital', 'Reports going to our investors look generic. Branding would help.', '#', '2026-05-18T09:00:00.000Z'),
('m11', 'req_009', 'Teams', 'Pavel Novak', 'Praha Capital', 'Auditor needs filtered logs by next month — currently I export everything.', '#', '2026-05-26T09:00:00.000Z'),
('m12', 'req_010', 'Teams', 'Greta Wahl', 'BlauBank', 'Would be nice to leave a note on a row so my colleague sees the context.', '#', '2026-05-17T09:00:00.000Z'),
('m13', 'req_011', 'Read.AI', 'Onboarding — NordBank', 'NordBank AS', 'We can''t roll out without Azure AD federation.', '#', '2026-05-22T09:00:00.000Z'),
('m14', 'req_012', 'Email', 'Frédéric Lambert', 'Parisien Capital', 'Can''t read the dashboard on my phone during travel.', '#', '2026-05-19T09:00:00.000Z'),
('m15', 'req_013', 'Teams', 'Jonas Lindqvist', 'NordBank AS', 'Give us a webhook on flag — we''ll pipe it into our SIEM.', '#', '2026-05-25T09:00:00.000Z'),
('m16', 'req_014', 'Email', 'Hannah Bauer', 'Helvetia Trust', 'Same filter every morning — save it, please.', '#', '2026-05-23T09:00:00.000Z'),
('m17', 'req_015', 'Teams', 'Mia Andersen', 'DeltaPay', 'Migrating segments — bulk edit would save days.', '#', '2026-05-15T09:00:00.000Z'),
('m18', 'req_016', 'Email', 'Ravi Shah', 'FinSquare', 'Push alerts to Slack — email is too noisy.', '#', '2026-05-24T09:00:00.000Z'),
('m19', 'req_017', 'Read.AI', 'QBR — Praha Capital', 'Praha Capital', 'We work in CZK — converting every report is painful.', '#', '2026-05-21T09:00:00.000Z'),
('m20', 'req_018', 'Teams', 'Pavel Novak', 'Praha Capital', 'When an entity''s score changes I need to explain why.', '#', '2026-05-22T09:00:00.000Z'),
('m21', 'req_019', 'Email', 'New user — DeltaPay', 'DeltaPay', 'What does ''PEP-proximity'' mean in the indicator list?', '#', '2026-05-16T09:00:00.000Z'),
('m22', 'req_020', 'Teams', 'Ravi Shah', 'FinSquare', 'We keep getting 429s — show us where we are vs the limit.', '#', '2026-05-23T09:00:00.000Z'),
('m23', 'req_021', 'Read.AI', 'Compliance review — Helvetia', 'Helvetia Trust', 'After we tighten a rule, we need to re-check the last quarter.', '#', '2026-05-24T09:00:00.000Z'),
('m24', 'req_022', 'Email', 'Hannah Bauer', 'Helvetia Trust', 'Retail and corporate should not share a threshold.', '#', '2026-05-22T09:00:00.000Z'),
('m25', 'req_023', 'Teams', 'Jonas Lindqvist', 'NordBank AS', 'Our SOC wants CEF feeds, not JSON dumps.', '#', '2026-05-20T09:00:00.000Z'),
('m26', 'req_024', 'Email', 'Various', 'Multiple', 'Aggregated: 5 separate ''portal feels slow'' complaints.', '#', '2026-05-14T09:00:00.000Z'),
('m27', 'req_025', 'Teams', 'Anonymous', 'DeltaPay', 'Could we have a light mode option?', '#', '2026-05-13T09:00:00.000Z');
